In [2]:
import numpy as np

In [6]:
#Normalize values between 0 and 1.
a = np.array([10, 20, 30, 40, 50])
normalized = (a - a.min()) / (a.max() - a.min())
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
#Find Missing Values
a = np.array([10, np.nan, 20, np.nan, 30])
np.isnan(a).sum()

np.int64(2)

In [12]:
#replace missing value with mean
a[np.isnan(a)] = np.nanmean(a)
print(a)

[10. 20. 20. 20. 30.]


In [20]:
#Find top 3 highest values.
np.sort(a)[-3,]

np.float64(20.0)

In [27]:
#Row-wise Mean in 2D Array
a = np.array([[10, 20], [30, 40]])

a.mean(axis=1)

array([15., 35.])

In [28]:
#column vise sum
a.sum(axis=0)

array([40, 60])

In [30]:
#Get values greater than average.
a[a> a.mean()]

array([30, 40])

In [31]:
#find index of max
np.argmax(a)

np.int64(3)

In [33]:
#Standard Deviation Calculation
np.std(a)

np.float64(11.180339887498949)

In [34]:
#Reshape Dataset for Model Input
np.reshape(-1,1)

array([-1])

In [40]:
#Find Correlation-like Operation
a = np.array([10, 20, 30, 40])
b = np.array([15, 25, 35, 45])


np.corrcoef(a, b)


array([[1., 1.],
       [1., 1.]])