In [1]:
import numpy as np

In [2]:
#Create NumPy Array
a= np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [12]:
#Create zero and ones Array
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#Create Range of Numbers
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
#reshape Array
arr=np.arange(1,7)
print (arr)
arr.reshape(2,3)

[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#basic Maths Operations
a1 = np.array([1,2,3,4])
a2 = np.array([4,3,2,1])

In [31]:
#Addition
print(a1+a2)

[5 5 5 5]


In [32]:
#Subsraction
print(a1-a2)

[-3 -1  1  3]


In [34]:
#Multiplication
print(a1*a2)

[4 6 6 4]


In [35]:
#Division
print(a1/a2)

[0.25       0.66666667 1.5        4.        ]


In [36]:
a=np.array([10,20,30,40])

#Calculate Mean
#formula =sum of array value/number of array values
cal_mean =np.mean(a)
print(cal_mean)

25.0


In [38]:
#Sum of Array Numbers
print(np.sum(a))

100


In [42]:
#Find Max Number in array
print(np.max(a))

40


In [41]:
#find min number in array
print(np.min(a))

10


In [43]:
#Indexing
print(a[1])

20


In [45]:
print(a[1:4])

[20 30 40]


In [48]:
#2D array
arr_2d= np.array([[1,2,3],[4,5,6]])

In [51]:
print(arr_2d[0,2])

3


In [52]:
print(arr_2d[1,2])

6


In [53]:
np.random.rand(2,3)

array([[0.33455322, 0.76510502, 0.5374913 ],
       [0.15680469, 0.90250062, 0.00954911]])

In [54]:
np.random.rand(23)

array([0.69103434, 0.94932269, 0.52221326, 0.24326796, 0.1006451 ,
       0.16934535, 0.59588291, 0.9893817 , 0.61164171, 0.69766345,
       0.18343496, 0.19348316, 0.74499412, 0.72429739, 0.14179222,
       0.9938814 , 0.25706292, 0.21841714, 0.14324567, 0.95655387,
       0.99840277, 0.69819876, 0.54831779])

In [58]:
np.random.randint(1,10,(2,4))

array([[2, 9, 3, 4],
       [9, 7, 2, 8]], dtype=int32)

In [59]:
a

array([10, 20, 30, 40])

In [60]:
a.shape

(4,)

In [61]:
a.ndim

1

In [62]:
arr_2d.shape

(2, 3)

In [63]:
arr_2d.ndim

2

In [67]:
#Flatten Array - collapsing a multi-dimensional array (like a matrix or a nested list) into a single, one-dimensional array.
a.flatten()

array([10, 20, 30, 40])

In [66]:
arr_2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [71]:
#Stack arrays vertically and horizontally
np.vstack((a,a1))

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [72]:
np.hstack((a,a1))

array([10, 20, 30, 40,  1,  2,  3,  4])

In [75]:
#increase the dimensionality of your data (e.g., turning a collection of 2D images into a single 3D "batch").
np.stack((a1,a2),axis = 0)

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [74]:
np.stack((a1,a2),axis = 1)

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [78]:
#find Unique Element
b=np.array([10, 20, 30, 30])
print(np.unique(b))

[10 20 30]


In [80]:
#matrix Multiplication
mat1 = np.array([[1, 2], 
              [3, 4]])

mat2 = np.array([[5, 6], 
              [7, 8]])
#using Numpy - type 1
print(np.dot(mat1,mat2))

[[19 22]
 [43 50]]


In [90]:
#Regular Calc - type 2
print(mat1@mat2)

[[19 22]
 [43 50]]


In [88]:
#type 3
print(np.matmul(mat1,mat2))

[[19 22]
 [43 50]]


In [93]:
#Replace values greater than 10 with 0.
a[a>30]=0
a

array([10, 20, 30,  0])